# Config for building https://did.readthedocs.io/
version: 2

python:
    install:
      - method: pip
        path: .
        extra_requirements: [all]
build:
    apt_packages:
      - python3-dev
      - libkrb5-dev
