# Config for building https://did.readthedocs.io/
version: 2

python:
    install:
      - method: pip
        path: .
        extra_requirements: [all]

build:
    os: ubuntu-22.04
    tools:
        python: "3.11"
    apt_packages:
      - python3-dev
      - libkrb5-dev
